micronaut:
  application:
    name: searchService
  metrics:
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M
    enabled: true
netty:
  default:
    allocator:
      max-order: 3
elasticsearch.httpHosts: http://localhost:9200,http://127.0.0.2:9200
